#! /bin/sh

# Generates all the support files while incorporating the test results

for f in computations; do
    if [ -r $f.tex ]; then
        if ../../scripts/extract-test-results -r $f-all-archs.tex ../tests.yaml  < $f.tex > $f-ann.tex;then
           pdflatex -interaction nonstopmode $f-ann.tex
           pdflatex -interaction nonstopmode $f-ann.tex
        fi
    fi
done
