#!/bin/sh
# A ruby script to regenerate all the icons files
#
# This script is intended to be run from a Linux machine with convert
# on.

convert QSoas-logo.svg QSoas.ico
rsvg-convert -w 256 -h 256 QSoas-logo.svg > QSoas-logo.png


mkdir -p tmp-icons
for res in 16 32 48 128 256 512; do
    rsvg-convert -w $res -h $res QSoas-logo.svg > tmp-icons/QSoas-$res.png
done
png2icns QSoas.icns tmp-icons/*.png
rm -rf tmp-icons

