#!/bin/sh
# A ruby script to regenerate all the icons files
#
# This script is intended to be run from a Linux machine with convert
# on.

# convert QSoas-logo.svg QSoas.ico
inkscape -w 256 -o QSoas-logo.png QSoas-logo.svg

# For the FB logo:
# inkscape -w 1536 -a -50:-50:530:530 -e ~/QSoas-logo.png QSoas-logo.svg

mkdir -p tmp-icons
for res in 16 32 48 64 96 128 256 512; do
    echo "Generating icon at $res"x"$res"
    inkscape -w $res -o tmp-icons/QSoas-$res.png QSoas-logo.svg
done
convert tmp-icons/*.png QSoas.ico
rm -f tmp-icons/*64*.png
rm -f tmp-icons/*96*.png
png2icns QSoas.icns tmp-icons/*.png
rm -rf tmp-icons

