#! /bin/bash

# This script takes the qsoas.kd documentation and creates the HTML
# and PDF documentation from it.

cat head.html <(echo 'Last updated on <b>'; date; echo '</b></p>') <(./preprocess-doc qsoas.kd | kramdown -o html) tail.html > qsoas.html
cat head.tex <(./preprocess-doc qsoas.kd | kramdown -o latex) tail.tex > qsoas.tex
if [ -r changes.kd ]; then
    cat head.html <(./preprocess-doc changes.kd qsoas.html | kramdown -o html) tail.html > changes.html
fi
cat head.html  <(./preprocess-doc faq.kd | kramdown -o html) tail.html > faq.html


