*DMPREC
      DOUBLE PRECISION FUNCTION DMPREC()
C***BEGIN PROLOGUE  DPREC
C***REFER TO  DODR,DODRC
C***ROUTINES CALLED  (NONE)
C***DATE WRITTEN   860529   (YYMMDD)
C***REVISION DATE  920304   (YYMMDD)
C***PURPOSE  DETERMINE MACHINE PRECISION FOR TARGET MACHINE AND COMPILER
C            ASSUMING FLOATING-POINT NUMBERS ARE REPRESENTED IN THE
C            T-DIGIT, BASE-B FORM
C                  SIGN (B**E)*( (X(1)/B) + ... + (X(T)/B**T) )
C            WHERE 0 .LE. X(I) .LT. B FOR I=1,...,T, AND
C                  0 .LT. X(1).
C            TO ALTER THIS FUNCTION FOR A PARTICULAR TARGET MACHINE,
C            EITHER
C                  ACTIVATE THE DESIRED SET OF DATA STATEMENTS BY
C                  REMOVING THE C FROM COLUMN 1 
C            OR
C                  SET B, TD AND TS USING I1MACH BY ACTIVATING
C                  THE DECLARATION STATEMENTS FOR I1MACH 
C                  AND THE STATEMENTS PRECEEDING THE FIRST 
C                  EXECUTABLE STATEMENT BELOW.
C***END PROLOGUE  DPREC

C...LOCAL SCALARS
      DOUBLE PRECISION
     +   B
      INTEGER 
     +   TD,TS


C...VARIABLE DEFINITIONS (ALPHABETICALLY)

C     DOUBLE PRECISION B
C        THE BASE OF THE TARGET MACHINE.
C        (MAY BE DEFINED USING I1MACH(10).)
C     INTEGER TD
C        THE NUMBER OF BASE-B DIGITS IN DOUBLE PRECISION.
C        (MAY BE DEFINED USING I1MACH(14).)
C     INTEGER TS
C        THE NUMBER OF BASE-B DIGITS IN SINGLE PRECISION.
C        (MAY BE DEFINED USING I1MACH(11).)


C   MACHINE CONSTANTS FOR COMPUTERS FOLLOWING IEEE ARITHMETIC STANDARD
C   (E.G., MOTOROLA 68000 BASED MACHINES SUCH AS SUN AND SPARC 
C   WORKSTATIONS, AND AT&T PC 7300; AND 8087 BASED MICROS SUCH AS THE
C   IBM PC AND THE AT&T 6300).
      DATA B  /   2 /
      DATA TS /  24 /
      DATA TD /  53 /

      DMPREC = B ** (1-TD)

      RETURN

      END
