#! /bin/sh


# Runs the test suite of QSoas, in

checks=memcheck
pref=
qsoas=$QSOAS
if [ -z "$qsoas" ]; then
    qsoas=QSoas
fi
xvfb="xvfb-run -a -s"
p1='-screen 0 1280x1024x24'
case $1 in
    --memcheck)
        pref="valgrind --tool=memcheck --track-origins=yes --leak-check=full --suppressions=../misc/valgrind.suppr "
        if [ "$2" ]; then
            pref="$pref --xml=yes --xml-file=../$2"
        fi
        shift
        ;;
    --helgrind)
        pref="valgrind --tool=helgrind "
        if [ "$2" ]; then
            pref="$pref --xml=yes --xml-file=../$2"
        fi
        shift
        ;;
    --callgrind)
        pref="valgrind --tool=callgrind --compress-strings=no --callgrind-out-file=../callgrind-output"
        # if [ "$2" ]; then
        #     pref="$pref --xml=yes --xml-file=../$2"
        # fi
        shift
        ;;
    --xml)
        for a in $checks; do
            echo "Running check $a:"
            $0 --$a $a".xml"
        done
        exit 0
        ;;
    --all)
        for a in $checks; do
            echo "Running check $a:"
            $0 --$a | tee $a.log 2>&1 
        done
        exit 0
        ;;
    --no-xvfb)
        xvfb=""
        p1=""
        shift
        ;;
esac

cd tests
$xvfb "$p1" $pref $qsoas --run '@ run-all-tests.cmds '$1 --exit-after-running
