#! /bin/sh

# This script automates the creation of the base files for macports,
# by building the base archive and setting up the version name
# correctly.
#
# It should be run from the QSoas/ directory (and not from the pkg/
# subdir)

version="$1"
if [ -z "$version" ]; then
    version=$(grep ^VERSION QSoas.pro | sed -r s/'.*=\s+'//)
    version="$version"+`date +%Y.%m.%d`
fi

if [ -z "$QSOAS_BUILDS" ]; then
    outdir=$HOME/tmp/qsoas
else
    outdir="$QSOAS_BUILDS"
fi
mkdir -p $outdir
echo "Preparing an archive and a portfile for version $version"
echo " -> saving in $outdir"
rm -rf $outdir/qsoas-$version

# copying directory
rsync -a --exclude build --exclude dox --exclude xml --exclude '*~' --exclude .git ./ $outdir/qsoas-$version

rm -f $outdir/qsoas-$version/QSoas
(
    cd $outdir/qsoas-$version/
    if [ -r tests/text-backends/generate-data.rb ]; then
        cd tests/text-backends
        echo "Generating the data for the tests"
        ruby generate-data.rb
        cd ../..
    fi

    # Regenerate the icons if needed
    if [ -x generate-icons ]; then
        echo "Generating the icons"
        ./generate-icons
    fi
    # Regenerate the Qt documentation if needed
    if [ -x doc/generate-help ]; then
        echo "Generating the Qt help files"
        cd doc;
        ./generate-help
    fi
)
(
    echo "Generating the qsoas-$version.tar.gz tarball"
    cd $outdir
    tar czf qsoas-$version.tar.gz qsoas-$version
    echo "Checking the tarball: "
    tar tvzf qsoas-$version.tar.gz
)

cat pkg/Portfile.base | sed 's/#VERSION#/'$version/g > $outdir/Portfile
